### PR TITLE
Added new "Triggers" button type

### PR DESCRIPTION
**Pull request by lindseydiloreto**
This PR adds a new type of button: **Triggers**

Instead of being a "radio button in disguise", a trigger acts more like an _actual button_. As in, you click it and something immediately happens.

There are two types of triggers... "Link" and "JavaScript".
- A **link trigger** is a straightforward link. Enter the URL of the page you would like to be taken to. You can optionally have the link open in a new window.
- A **JavaScript trigger** will run whatever JS you specify. Generally speaking, it'll make sense to simply call a function, which would enact more complex behavior.

Button Box is awesome, I hope you find this PR useful! Please let me know if you have any questions. :)

### CODE REVIEW

**Comment by lindseydiloreto** [comment]
Here's a practical example...

settings-example

For the JavaScript trigger, `emailCustomer` would be a custom user function, which could trigger anything they want. That JS function would have to be [included separately](https://github.com/lindseydiloreto/craft-cpjs), but it could be as simple or complex as they need. It could even trigger a controller action... the possibilities are nearly endless!

**Comment by lindseydiloreto** [comment]
Just added the ability to **parse element tags in links**.

**EXAMPLES:**

A link to view the "notes" of this entry on the front-end...

    {url}#notes

JS to send an email about this entry...

    sendEntryMessage({id});

---

In the examples above, `{url}` and `{id}` will be parsed from the current element. And just like [dynamic entry titles](https://craftcms.com/docs/sections-and-entries#dynamic-entry-titles), any element field handle can be used.

**Comment by joshangell** [comment]
I will merge this soon, I promise! Just fighting the tide of client work ...

**Comment by lindseydiloreto** [comment]
Lol, sounds good. :)

**Comment by lindseydiloreto** [comment]
Hi Josh! I don't suppose you've had a chance to look at this yet?

**Comment by joshangell** [comment]
Hey Lindsey, sorry I didn’t have time in the end - I’ve passed this over to @Nav33d who is taking over maintenance of this project. I don’t see any reason why it can’t just be merged, but it probably makes sense to test it out first.

**Comment by lindseydiloreto** [comment]
Thanks @joshangell!

Hi @Nav33d! Would you mind taking a look at this PR? I've found this feature to be _extremely_ helpful, and it works beautifully within the larger context of the Button Box plugin.

Please let me know if you have any questions! :)

**Comment by Nav33d** [comment]
Hi @lindseydiloreto,

Apologies for the delayed reply! I have now merged the pull request.

Many thanks

**Comment by lindseydiloreto** [comment]
Fantastic, thanks @Nav33d! :)

Would you mind mentioning the Trigger type in the README and/or [docs](http://plugins.supercooldesign.co.uk/plugin/button-box/docs/field)? There are some examples at the [top of this thread](https://github.com/supercool/Button-Box/pull/11#issuecomment-230134186) which you could use on the site.

Let me know if you need anything else from me! :)

**Pull request merged**
